-- init sql --
DROP TABLE IF EXISTS `u_user`;
CREATE TABLE `u_user` (
  `USERID` varchar(36) NOT NULL COMMENT '主键',
  `USERNAME` varchar(100) NOT NULL COMMENT '登录账号',
  `REALNAME` varchar(100) NOT NULL COMMENT '真实姓名',
  `PASSWORD` varchar(100) NOT NULL COMMENT '密码',
  `SITEID` varchar(36) DEFAULT '' COMMENT '所属单位，外键，引用U_SITE表',
  `ROLECODE` varchar(30) DEFAULT NULL COMMENT '用户角色编码',
  `MOBILE` varchar(50) DEFAULT NULL COMMENT '手机',
  `SEX` varchar(50) DEFAULT NULL COMMENT '性别',
  `EMAIL` varchar(50) DEFAULT NULL COMMENT '邮箱',
  `GENDERCODE` varchar(20) DEFAULT NULL COMMENT '字典中性别的编码',
  `BIRTHDAY` datetime DEFAULT NULL COMMENT '出生日期',
  `CREATETIME` datetime DEFAULT NULL COMMENT '记录添加时间',
  `CREATEUSER` varchar(36) DEFAULT NULL COMMENT '记录添加者',
  `UPDATETIME` datetime DEFAULT NULL COMMENT '记录最后一次修改时间',
  `UPDATEUSER` varchar(36) DEFAULT NULL COMMENT '记录最后一次修改者',
  `PHOTO` longtext DEFAULT NULL COMMENT '用户照片',
  `REGIONCODE` varchar(50) DEFAULT NULL COMMENT '位置编码',
  `SALT` varchar(100) DEFAULT NULL COMMENT '盐值',
  `STATUS` int(10) DEFAULT 0 COMMENT '0锁定 1解锁',

  PRIMARY KEY (`USERID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;


DROP TABLE IF EXISTS `sys_role`;
CREATE TABLE `sys_role` (
  `ROLEID` varchar(36) NOT NULL COMMENT '主键',
  `USERID` varchar(36) NOT NULL COMMENT '用户ID',
  `ROLES` varchar(100) NOT NULL COMMENT '权限',
  PRIMARY KEY (`ROLEID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;

DROP TABLE IF EXISTS `stu_bsc`;
CREATE TABLE `stu_bsc` (
  `BSCID` varchar(36) NOT NULL COMMENT '主键',
  `NAME` varchar(50) NOT NULL COMMENT '名称',
  `TYPE` varchar(50) NOT NULL COMMENT '类别',
  `TEXT` LONGTEXT NOT NULL COMMENT '内容',
  `CREATETIME` datetime NOT NULL COMMENT '创建时间',
  `CREATEBY` varchar(100) NOT NULL COMMENT '创建人',
  PRIMARY KEY (`BSCID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;

DROP TABLE IF EXISTS `u_attachment`;
CREATE TABLE `u_attachment` (
  `ATTID` varchar(36) NOT NULL COMMENT '主键',
  `BUSINESSID` varchar(50) NOT NULL COMMENT '名称',
  `ORIGINALFILENAME` varchar(50) NOT NULL COMMENT '名称',
  `ACTUALFILENAME` varchar(50) NOT NULL COMMENT '名称',
  `FILESIZE` varchar(50) NOT NULL COMMENT '名称',
  `FILETYPE` varchar(50) NOT NULL COMMENT '名称',
  `CREATETIME` datetime NOT NULL COMMENT '创建时间',
  PRIMARY KEY (`ATTID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;

DROP TABLE IF EXISTS `stu_memo`;
CREATE TABLE `stu_memo` (
  `MEMOID` varchar(36) NOT NULL COMMENT '主键',
  `NAME` varchar(50) NOT NULL COMMENT '名称',
  `TEXT` LONGTEXT NOT NULL COMMENT '内容',
  `CREATETIME` datetime NOT NULL COMMENT '创建时间',
  `HOPETIME` datetime  COMMENT '期望完成时间',
  `CREATEBY` varchar(100) NOT NULL COMMENT '创建人',
  `FINISHED` int(10) DEFAULT 0 COMMENT '0未完成 1已完成',
  PRIMARY KEY (`MEMOID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;

DROP TABLE IF EXISTS `stu_mistake`;
CREATE TABLE `stu_mistake` (
  `MISTAKEID` varchar(36) NOT NULL COMMENT '主键',
  `NAME` varchar(50) NOT NULL COMMENT '名称',
  `LEVEL` int(10) DEFAULT 1 COMMENT '等级',
  `COUNT` int(10) DEFAULT 0 COMMENT '关注次数',
  `TEXT` LONGTEXT NOT NULL COMMENT '内容',
  `CREATETIME` datetime NOT NULL COMMENT '创建时间',
  `CREATEBY` varchar(100) NOT NULL COMMENT '创建人',
  PRIMARY KEY (`MISTAKEID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;

DROP TABLE IF EXISTS `stu_demo_code`;
CREATE TABLE `stu_demo_code` (
  `CODEID` varchar(36) NOT NULL COMMENT '主键',
  `NAME` varchar(50) NOT NULL COMMENT '名称',
  `CODETYPE` varchar(50)  COMMENT '标签',
  `LOOKCOUNT` int(10) DEFAULT 0 COMMENT '热度',
  `TEXT` LONGTEXT NOT NULL COMMENT '内容',
  `CREATETIME` datetime NOT NULL COMMENT '创建时间',
  `CREATEBY` varchar(100) NOT NULL COMMENT '创建人',
  PRIMARY KEY (`CODEID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;
