#server
server.context-path: /EasyTom
server.port: 8821

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/easytom?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    initialSize: 1
    minIdle: 3
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,slf4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    useGlobalDataSourceStat: true

mybatis-plus:
  mapper-locations: classpath:/mapper/*/*Mapper.xml

spring.thymeleaf:
  cache: false

spring.cache:
  type: ehcache
  ehcache:
  config: classpath:ehcache.xml

#MVC
spring.resources:
  cache-period: 604800
  chain:
    gzipped: true
    cache: true



# 上传文件大小限制
spring.http.multipart:
  max-file-size: 30Mb
  max-request-size: 30Mb

# 允许多文件上传
multipart.enabled: true

core.security.shiro:
  loginUrl: http://localhost:8821/EasyTom/ui/frontend/login
  successUrl: http://localhost:8821/EasyTom/ui/frontend/login
  filterChainDefinitionMap:
    /static/**: anon
    /api/**: anon
    /cas: cas
    /tom/**: anon
#文件保存前缀
tom.files.path: D:/fcFiles/
